### PR TITLE
Add angled IDC headers

### PR DESCRIPTION
**Pull request by fauxpark**
Modified the straight header footprints with the outline based on [this datasheet](http://katalog.we-online.de/em/datasheet/6120xx21721.pdf). The bumps on the "bottom" of the header are not counted.

Not sure if I should move the pin 1 marker in the 2x03 header slightly to the left so it doesn't intersect with the key cutout silkscreen.

Also added 3D model references to all footprints to appease the KLC script.

footprint
3d

### CODE REVIEW

**Comment by fauxpark** [comment]
Actually, it looks like I missed the keying in the datasheet - the 3D models for these new footprints would show the key closest to the board, whereas the datasheet has the key at the top of the header and the pinout reversed. Technically these footprints are the same as the straight headers, but perhaps there should be variants for both directions?

**Comment by SchrodingersGat** [comment]
@fauxpark yes the pinout is reversed from what is in the datasheet - please rotate the pins 180 degrees!

Also:

Pin-1 marker on the silkscreen layer should be placed next to pin-1. currently it is under the body of the connector, and would not actually be visible once the connector has been loaded onto the board!

**Comment by fauxpark** [comment]
Will do. As for the pin 1 marker, I noted that but wasn't sure what to do since the straight headers also have this problem. and the script hasn't been taught to pick it up yet. I will move the triangle up to the pin. Is there a standard/KLC for pin 1 markers?

**Comment by poeschlr** [comment]
@fauxpark wrote:
> I will move the triangle up to the pin. Is there a standard/KLC for pin 1 markers?

Yes see [FAQ section silk layer](https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions#silkscreen-layer)

**Comment by fauxpark** [comment]
Thanks @poeschlr.

Here's what the new footprints look like. I took some cues from the pin header footprints:
fp
3d

**Comment by SchrodingersGat** [comment]
@fauxpark thanks this is much better :)

**Pull request merged**
